[tool.poetry]
name = "tritium-pipeline"
version = "0.3.0"
description = "Log based job pipeline tool"
authors = ["voidpointercast <patrick.daniel.gress@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.0"
toolz = "^0.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
