
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T09:20:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0188e5d425609630e5508e9ce1250ec1641c6a60",
 "version": "5.0.0-a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
