
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-09T13:34:02-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "653a82f23f706a7abaa751effb7b3d8f2f0d4794",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
