[tool.poetry]
name = "dw-core"
version = "0.0.3"
description = "Core library for DeskWatch"
authors = ["Kohinoor Bharti <kohinoorbharti7@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://deskwatch.net/"
repository = "https://github.com/DeskWatch/dw-core/"
documentation = "https://docs.deskwatch.net/"
packages = [
    { include = "dw_core" },
    { include = "dw_datastore" },
    { include = "dw_transform" },
    { include = "dw_query" },
]

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "^3.1"
peewee = "3.*"
appdirs = "^1.4.3"
iso8601 = "^0.1.12"
python-json-logger = "*"
TakeTheTime = "^0.3.1"
pymongo = {version = "^3.10.0", optional = true}
strict-rfc3339 = "^0.7"
tomlkit = "*"
deprecation = "*"
timeslot = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.8.1"
mypy = "*"
pylint = "^2.4.4"

[tool.poetry.extras]
mongo = ["pymongo"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
