# Version file autogenerated by the build process
version = '0.9.1'
build = 1041
vcs_info = 'Git SHA1 9365edde committed on 2022-03-03'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.9.1"\nKSCONF_BUILD="1041"\nKSCONF_VCS_INFO="Git SHA1 9365edde committed on 2022-03-03"')
