# coding: utf-8

"""
    LEIA RESTful API for AI

    Leia API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact:
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leiaapi.generated
from leiaapi.generated.models.login_token import LoginToken  # noqa: E501
from leiaapi.generated.rest import ApiException


class TestLoginToken(unittest.TestCase):
    """LoginToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginToken(self):
        """Test LoginToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leiaapi.generated.models.login_token.LoginToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
