# coding: utf-8

"""
    LEIA RESTful API for AI

    Leia API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leiaapi.generated
from leiaapi.generated.models.job_types import JobTypes  # noqa: E501
from leiaapi.generated.rest import ApiException


class TestJobTypes(unittest.TestCase):
    """JobTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobTypes(self):
        """Test JobTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leiaapi.generated.models.job_types.JobTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
