# coding: utf-8

"""
    LEIA RESTful API for AI

    Leia API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leiaapi.generated
from leiaapi.generated.api.application_api import ApplicationApi  # noqa: E501
from leiaapi.generated.rest import ApiException


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_application(self):
        """Test case for login_application

        Logs into Leia API  # noqa: E501
        """
        pass

    def test_logout_application(self):
        """Test case for logout_application

        Logs out from Leia API  # noqa: E501
        """
        pass

    def test_who_am_i(self):
        """Test case for who_am_i

        Gets the currently connected application  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
