
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-08T13:50:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3a02b788c8295c6087c72ce31ddb146ebb9b804",
 "version": "0.0.67.post0.dev128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
