
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-07T11:08:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "978bc295edf32b76bdaf627bf01207b4186fb2e3",
 "version": "0.7.1.post.dev411"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
