version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip install aldryn_client divio-cli
            sudo pip install -e . 

      - run:
          name: Validate Addon
          command: |
            divio addon validate

