[tool.poetry]
name = "scatterbrain"
version = "0.1.11"
description = ""
authors = ["Christina Hedges <christina.l.hedges@nasa.gov>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
numpy = "^1.21.2"
matplotlib = "^3.4.3"
fitsio = "^1.1.5"
tqdm = "^4.62.3"
scipy = "^1.7.1"
fbpca = "^1.0"
astropy = "^4.3.1"
tess-ephem = "^0.3.0"
tess-locator = "^0.5.0"
multiprocess = "^0.70.12"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyterlab = "<3.1.14"
isort = "^5.9.3"
flake8 = "^3.9.2"
mkdocs = "^1.2.2"
mkdocstrings = "^0.16.2"
mkdocs-material = "^7.3.1"
pytkdocs = {version = "^0.12.0", extras = ["numpy-style"]}
mkdocs-jupyter = "^0.18.0"
lightkurve = "^2.0.11"
tess-locator = "^0.5.0"
tables = "^3.6.1"
markdown-include = "^0.6.0"
mkdocs-include-markdown-plugin = "^3.2.3"
line-profiler = "^3.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
