[[bin]]
name = "pngquant"
path = "rust/bin.rs"

[build-dependencies]
cc = "1.0.71"
dunce = "1.0.2"

[dependencies]
getopts = "0.2.21"
libc = "0.2.106"
libpng-sys = "1.1.8"
wild = "2.0.4"

[dependencies.cocoa_image]
optional = true
version = "1.0.4"

[dependencies.imagequant-sys]
path = "local_dependencies/imagequant-sys"
version = "3.0.2"

[dependencies.lcms2-sys]
optional = true
version = "3.1.9"

[dependencies.openmp-sys]
optional = true
version = "1.2.0"

[features]
alloc_system = []
cocoa = ["cocoa_image"]
default = ["sse", "lcms2"]
lcms2 = ["lcms2-sys"]
lcms2-static = ["lcms2", "lcms2-sys/static"]
openmp = ["openmp-sys", "imagequant-sys/openmp"]
openmp-static = ["openmp", "openmp-sys/static", "imagequant-sys/openmp-static"]
png-static = ["libpng-sys/static"]
sse = ["imagequant-sys/sse"]
static = ["lcms2-static", "png-static", "openmp-static"]
z-static = ["libpng-sys/static-libz"]

[package]
authors = ["Kornel Lesiński <kornel@pngquant.org>"]
build = "rust/build.rs"
categories = ["multimedia::images"]
description = "Convert 24/32-bit images to 8-bit palette with alpha channel.\nBindings for libimagequant that powers pngquant lossy PNG compressor.\n\nDual-licensed like pngquant. See https://pngquant.org for details."
documentation = "https://github.com/kornelski/pngquant#readme"
edition = "2018"
homepage = "https://pngquant.org"
include = ["/rwpng*.[ch]", "/pngquant.c", "/pngquant_opts.[ch]", "/rust/*.rs", "/COPYRIGHT", "/Cargo.toml", "/README.md", "/pyproject.toml"]
keywords = ["quantization", "palette", "image", "pngquant", "compression"]
license = "GPL-3.0+"
name = "pngquant"
readme = "README.md"
repository = "https://github.com/kornelski/pngquant.git"
version = "2.17.0"
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
[profile.release]
lto = true
