[build-system]
requires = [
    "setuptools>=42",
    "wheel",
	"pydub",
	"python_anticaptcha",
	"requests",
	"selenium",
	"SpeechRecognition",
	"stem",
	"undetected_chromedriver"
]
build-backend = "setuptools.build_meta"