
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T20:21:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f02e45b17c7a8922127372e837277ace77639bf1",
 "version": "0.0.67.post0.dev110"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
