
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T11:08:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e050a52ac394b9fe7f088caf52ead51a84bcb9c",
 "version": "0.7.1.post.dev399"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
