# Generated by Django 2.2.12 on 2022-03-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tahoe_sites', '0003_auto_20220223_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganizationmapping',
            name='is_active',
        ),
    ]
