[tool.poetry]
name = "HeliumHelper"
version = "0.1.0"
description = ""
authors = ["Nathan Pirhalla <steelersfan5052@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
pandas = "^1.4.1"
flatdict = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
