[tool.poetry]
name = "xxp"
version = "22.3a1"
description = "xxd ripoff"
authors = [
    "Nick Timkovich <prometheus235@gmail.com>",
]
license = "MIT"
packages = [
    { include = "xxp", from = "src" },
]

readme = "README.md"
repository = "https://github.com/nicktimko/xxd"
keywords = ["binary", "hexdump"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[tool.pytest.ini_options]
pythonpath = ["src"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
