[tool.poetry]
name = "sheet-loader"
version = "0.0.1"
description = "Description"
authors = ["Daniel Sullivan <mumblepins@users.noreply.github.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/mumblepins/sheet-loader/"
documentation = "https://mumblepins.github.io/sheet-loader/"
readme = "README.md"
packages = [{ include = "sheet_loader", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
s3path = { version = "^0.3.3", optional = true }
fastapi = { version = "^0.74.1", optional = true }
pandas = "^1.4.1"
chardet = "^4.0.0"

[tool.poetry.dev-dependencies]
black = { version = "^22", allow-prereleases = true }
Sphinx = "^4.4"
sphinx-rtd-theme = "^1.0"
pre-commit = "^2.17.0"


[tool.poetry.extras]
s3path = ['s3path']
fastapi = ['fastapi']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.cache
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
