
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T08:54:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0255e13ff9945bafaa19542d9b6a5c3ffb3c90b2",
 "version": "2614"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
