# coding: utf-8

"""
    Conquest API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


# from __future__ import absolute_import

import unittest

import conquest
from conquest.models.conquest_api_reverse_action_completion_command import ConquestApiReverseActionCompletionCommand  # noqa: E501
from conquest.rest import ApiException


class TestConquestApiReverseActionCompletionCommand(unittest.TestCase):
    """ConquestApiReverseActionCompletionCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConquestApiReverseActionCompletionCommand(self):
        """Test ConquestApiReverseActionCompletionCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = conquest.models.conquest_api_reverse_action_completion_command.ConquestApiReverseActionCompletionCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
