# coding: utf-8

"""
    Conquest API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


# from __future__ import absolute_import

import unittest

import conquest
from conquest.api.action_service_api import ActionServiceApi  # noqa: E501
from conquest.rest import ApiException


class TestActionServiceApi(unittest.TestCase):
    """ActionServiceApi unit test stubs"""

    def setUp(self):
        self.api = conquest.api.action_service_api.ActionServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_action_service_apply_standard_action(self):
        """Test case for action_service_apply_standard_action

        """
        pass

    def test_action_service_complete_action(self):
        """Test case for action_service_complete_action

        """
        pass

    def test_action_service_create_succeeding_action(self):
        """Test case for action_service_create_succeeding_action

        """
        pass

    def test_action_service_delete_action(self):
        """Test case for action_service_delete_action

        """
        pass

    def test_action_service_get_action(self):
        """Test case for action_service_get_action

        """
        pass

    def test_action_service_get_action_completion_details(self):
        """Test case for action_service_get_action_completion_details

        """
        pass

    def test_action_service_move_action(self):
        """Test case for action_service_move_action

        """
        pass

    def test_action_service_reverse_action_completion(self):
        """Test case for action_service_reverse_action_completion

        """
        pass

    def test_action_service_update_action(self):
        """Test case for action_service_update_action

        """
        pass


if __name__ == '__main__':
    unittest.main()
