# coding: utf-8

"""
    Conquest API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


# from __future__ import absolute_import

import unittest

import conquest
from conquest.models.conquest_api_geo_package_table_description_options import ConquestApiGeoPackageTableDescriptionOptions  # noqa: E501
from conquest.rest import ApiException


class TestConquestApiGeoPackageTableDescriptionOptions(unittest.TestCase):
    """ConquestApiGeoPackageTableDescriptionOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConquestApiGeoPackageTableDescriptionOptions(self):
        """Test ConquestApiGeoPackageTableDescriptionOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = conquest.models.conquest_api_geo_package_table_description_options.ConquestApiGeoPackageTableDescriptionOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
