# coding: utf-8

"""
    Conquest API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


# from __future__ import absolute_import

import unittest

import conquest
from conquest.models.conquest_api_list_standard_defect_responses_query import ConquestApiListStandardDefectResponsesQuery  # noqa: E501
from conquest.rest import ApiException


class TestConquestApiListStandardDefectResponsesQuery(unittest.TestCase):
    """ConquestApiListStandardDefectResponsesQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConquestApiListStandardDefectResponsesQuery(self):
        """Test ConquestApiListStandardDefectResponsesQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = conquest.models.conquest_api_list_standard_defect_responses_query.ConquestApiListStandardDefectResponsesQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
