# coding: utf-8

"""
    Conquest API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


# from __future__ import absolute_import

import unittest

import conquest
from conquest.api.system_service_api import SystemServiceApi  # noqa: E501
from conquest.rest import ApiException
from . import api_instance

class TestSystemServiceApi(unittest.TestCase):
    """SystemServiceApi unit test stubs"""

    def setUp(self):
        self.api = conquest.api.system_service_api.SystemServiceApi(api_instance)  # noqa: E501

    def tearDown(self):
        pass

    def test_system_service_application_version(self):
        """Test case for system_service_application_version

        """
        version = self.api.system_service_application_version_with_http_info()
        self.assertTrue(200 in version)


if __name__ == '__main__':
    unittest.main()
