# coding: utf-8

"""
    Conquest API v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


# from __future__ import absolute_import

import unittest

import conquest
from conquest.models.conquest_api_job_key import ConquestApiJobKey  # noqa: E501
from conquest.rest import ApiException


class TestConquestApiJobKey(unittest.TestCase):
    """ConquestApiJobKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConquestApiJobKey(self):
        """Test ConquestApiJobKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = conquest.models.conquest_api_job_key.ConquestApiJobKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
