[tool.poetry]
name = "ibfs"
version = "0.1.0"
description = "Mount instabase filesystem API locally"
authors = ["Arjoonn Sharma <arjoonn.sharma@instabase.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fusepy = "^3.0.1"
click = "^8.0.3"
PyYAML = "^6.0"
requests = "^2.27.1"
ujson = "^5.1.0"
tqdm = "^4.62.3"
trieregex = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
