
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T17:19:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc9f30a56ed808f34db7556411de6e52364733ff",
 "version": "0.0.67.post0.dev100"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
