[tool.poetry]
name = "column_print"
version = "0.3.0"
description = "A simple way to print short strings to a terminal in columns."
authors = ["SteveDaulton <stevedaulton@gmail.com>"]
license = "GPL-2.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
Sphinx = "pylint"
flake8 = "^4.0.1"
pylint = "^2.12.2"
sphinx-rtd-theme = "^1.0.0"
twine = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
