name: CI
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Pylint test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint kili
  recipes:
    runs-on: ubuntu-latest
    name: Recipes test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert nbformat pytest

      - name: Run all tests and tested notebooks
        run: pytest -s
        env:
          KILI_API_CLOUD_VISION: ${{ secrets.KILI_API_CLOUD_VISION }}
          KILI_API_ENDPOINT: https://staging.cloud.kili-technology.com/api/label/v2/graphql
          KILI_USER_API_KEY: ${{ secrets.KILI_USER_API_KEY }}
          KILI_USER_EMAIL: ${{ secrets.KILI_USER_EMAIL }}
          KILI_USER_ID: ${{ secrets.KILI_USER_ID }}
