[tool.poetry]
name = "holyshit"
version = "1.0.1"
description = "Asynchronous experimental wrapper for the holyshit.wtf API"
authors = ["cobaltgit <criterion@chitco.co.uk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = ">=3.6.0"

[tool.poetry.dev-dependencies]
isort = "^4.0.2"
autoflake = "^1.4"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
