[tool.poetry]
name = "driva-python-sdk"
version = "0.4.0"
description = "Driva Python Sdk"
authors = ["Victor Hugo <victor@datadriva.com>"]
license = "GPL-3.0"
readme = "README.rst"
homepage = "https://github.com/victordriva/driva-python-sdk"
repository = "https://github.com/victordriva/driva-python-sdk"
documentation = "https://driva-python-sdk.readthedocs.io"
classifiers = [
    "Development Status :: 1 - Planning",
]
include = ["driva_python_sdk/py.typed"]

[tool.poetry.urls]
Changelog = "https://github.com/victordriva/driva-python-sdk/releases"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
pydantic = {extras = ["dotenv"], version = "^1.9.0"}
requests = "^2.27.1"
python-schema-registry-client = "^2.2.2"
kafka-python = "^2.0.2"
pydantic-avro = ">=0.2.4,<0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
coverage = {extras = ["toml"], version = "^6.1"}
safety = "^1.10.3"
mypy = "^0.931"
typeguard = "^2.13.2"
xdoctest = {extras = ["colors"], version = "^0.15.10"}
sphinx = "^4.3.0"
sphinx-autobuild = ">=2021.3.14"
pre-commit = "^2.15.0"
flake8 = "^4.0.1"
black = ">=21.10b0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.1"
reorder-python-imports = "^2.6.0"
pre-commit-hooks = "^4.0.1"
sphinx-click = "^3.0.2"
Pygments = "^2.10.0"
pyupgrade = "^2.29.1"
furo = ">=2021.11.12"
types-requests = "^2.27.11"
pytest-mock = "^3.7.0"
nox-poetry = "^0.9.0"
nox = "^2022.1.7"

[tool.poetry.scripts]
driva-python-sdk = "driva_python_sdk.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["driva_python_sdk", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
