
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-09T23:07:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b9108993883c80280318d08efe273f50943dbb6",
 "version": "0.8.21b0.dev202203100713"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
