[tool.pytest.ini_options]
addopts = '''
    --cache-clear
    --exitfirst
    --quiet
    tests/
'''

[tool.coverage.report]
fail_under = 95
precision = 2
show_missing = true
skip_covered = true

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39", "py310"]
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | __pycache__
  | build
  | dist
  | \.tox
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 88
lines_after_imports = 2
skip = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  ".tox",
  ".pytest_cache",
]
