
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T18:20:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b647cc157c7c292238c29891c77ab82fafadb4c3",
 "version": "3.0.0dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
