[tool.poetry]
name = "fluigent_sdk"
version = "0.0.1"
description = "Placeholder for fluigent_sdk by Fluigent"
authors = ["Paul Müller <dev@craban.de>"]
license = "None"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
