name: Test built
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup
        run: pip install ga4gh.gks.metaschema
      - name: Make
        run: cd schema && make all
