version: 2.1
orbs:
  docker: circleci/docker@1.6.0

jobs:
  test_package:
    docker:
      - image: circleci/python:3.8.5
    working_directory: /tmp/src/mriqc_learn
    steps:
      - checkout
      - run:
          name: Prepare environment & build
          command: |
            python3 -m venv /tmp/buildenv
            source /tmp/buildenv/bin/activate
            python -m pip install -U "setuptools~=58.0" "setuptools_scm>=6.2" pip wheel twine docutils
            python setup.py sdist bdist_wheel
            twine check dist/mriqc_learn*
      - store_artifacts:
          path: /tmp/src/mriqc_learn/dist
      - persist_to_workspace:
          root: /tmp/src/mriqc_learn
          paths: dist
      - run:
          name: Install on separate environment and check version [sdist]
          command: |
            python3 -m venv /tmp/install_sdist
            source /tmp/install_sdist/bin/activate
            python -m pip install -U pip "setuptools~=58.0" "setuptools_scm>=6.2"
            THISVERSION=$( python setup.py --version )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            python -m pip install dist/mriqc-learn*.tar.gz
            INSTALLED_VERSION=$(python -c 'import mriqc_learn as ml; print(ml.__version__, end="")')
            echo "VERSION: \"${THISVERSION}\""
            echo "INSTALLED: \"${INSTALLED_VERSION}\""
            test "${INSTALLED_VERSION}" = "${THISVERSION}"
      - run:
          name: Install on separate environment and check version [wheel]
          command: |
            python3 -m venv /tmp/install_wheel
            source /tmp/install_wheel/bin/activate
            python -m pip install "setuptools~=58.0" "setuptools_scm>=6.2" wheel "pip>=10.0.1"
            THISVERSION=$( python setup.py --version )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            python -m pip install dist/mriqc_learn*.whl
            INSTALLED_VERSION=$(python -c 'import mriqc_learn as ml; print(ml.__version__, end="")')
            echo "VERSION: \"${THISVERSION}\""
            echo "INSTALLED: \"${INSTALLED_VERSION}\""
            test "${INSTALLED_VERSION}" = "${THISVERSION}"

  deploy_pypi:
    docker:
      - image: circleci/python:3.8.5
    working_directory: /tmp/src/mriqc_learn
    steps:
      - attach_workspace:
          at: /tmp/src/mriqc_learn
      - run:
          name: Upload to Pypi
          command: |
            python3 -m venv /tmp/upload
            source /tmp/upload/bin/activate
            python -m pip install twine
            python -m twine check dist/*
            python -m twine upload dist/* --non-interactive

workflows:
  version: 2
  build_deploy:
    jobs:
      - test_package:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - deploy_pypi:
          requires:
            - test_package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
