
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-07T20:48:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6cd9793cace084d5f0f5e6e0fc7755be0730d62",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
