[tool.poetry]
name = "coinbasepro-revived"
version = "1.1.11"
description = "Revived https://github.com/danpaquin/coinbasepro-python. Python package to interact with the coinbase pro api https://docs.pro.coinbase.com/."
authors = ["me"]
packages = [
  { include = "cbpro" }
]

[tool.poetry.dependencies]
python = "^3.6"
sortedcontainers = "^2.0"
requests = "^2.13.0"
six = "^1.10.0"
websocket-client = ">=0.40.0,<1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
python-dateutil = "^2.7.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
