name: publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit message
        uses: adityaa30/check-commit@master
        with:
          max-header-length: 255

  test:
    name: Run pytest
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests
        run: pytest

  build-and-run-docker-image:
    if: github.event_name == 'pull_request'
    name: Docker build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download previous result info
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish.yml
          workflow_conclusion: success
          name: next_result
          path: ./
          check_artifacts: true
      - name: Set environment variable
        run: echo "PREVIOUS_SEQUENCE=$(cat ./next_result.txt)" >> $GITHUB_ENV
      - name: Download previous result
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish.yml
          workflow_conclusion: success
          name: results
          path: ./all_previous_results/
          check_artifacts: true
      - name: Copy necessary artifacts
        run: |
          mkdir -p previous_results/recordings
          cp -r ./all_previous_results/recordings/${{ env.PREVIOUS_SEQUENCE }} ./previous_results/recordings
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          docker build -t changeanalyzer:latest .
          # Replay & compare
          docker run -v $(pwd)/previous_results:/home/localtester/previous_results:Z --security-opt seccomp=./chrome.json changeanalyzer "--ini=[driver]\ncommand_executor=http://127.0.0.1:9515\nplatform=web\nurl=https://learn.ivves.eu/" -r -c --csv=/home/localtester/previous_results
          # Generate
          # docker run -v $(pwd)/previous_results:/home/localtester/previous_results:Z --security-opt seccomp=./chrome.json changeanalyzer "--ini=[driver]\ncommand_executor=http://127.0.0.1:9515\nplatform=web\nurl=https://learn.ivves.eu/" -g
          mkdir docker_results
          docker cp $(docker ps -alq):/home/localtester/change-analyzer/recordings ./docker_results
          docker cp $(docker ps -alq):/home/localtester/next_result.txt ./next_result.txt
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./docker_results
      - uses: actions/upload-artifact@v2
        with:
          name: next_result
          path: ./next_result.txt

  release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          sudo apt -y install python3-setuptools
          git config user.email "semantic-release"
          git config user.name "semantic-release"
          make publish
