[tool.poetry]
name = "pydelica"
version = "0.3.1"
description = "Light-weight serverless API for OpenModelica"
authors = ["Kristian Zarebski <krizar312@gmail.com>"]
license = "MIT"
keywords = ["modelica", "openmodelica"]
repository = "https://gitlab.com/krizar/pydelica"
readme = "README.md"
include = [
    "LICENSE"
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Scientific/Engineering",
    "Natural Language :: English",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research"
]

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.6.2"
pandas = "^1.2.2"
defusedxml = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.7.4"
black = {version = "^21.6b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"