#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @PypiSeedTag: Main
# @Project : codelife


"""
generated by PypiSeed(PPC) - Main Program
"""

import codelife.mainview as mv


def main():
    mv.MainView().start_app()


if __name__ == '__main__':
    main()




