[tool.poetry]
name = "flon"
version = "0.2.0"
description = "FLON parser for Python"
authors = ["Maximillian Strand <maximillian.strand@gmail.com>"]
repository = "https://gitlab.com/flon-lang/pyflon"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
