[tool.poetry]
name = "dfrost"
version = "0.1.8"
description = ""
authors = ["tlonny <t@lonny.io>"]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.20.51"
pathspec = "^0.9.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pylama = "^8.3.7"
pyflakes = "^2.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dfrost = 'dfrost.cli:run'
