version: 2

jobs:
  image-tests-mpl212:
    docker:
      - image: astropy/image-tests-py36-mpl212:1.10
    steps:
      - checkout
      - run:
          name: Install wheel
          command: pip3 install wheel
      - run:
          name: Install dependencies
          command: pip3 install .[test] codecov
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpl222:
    docker:
      - image: astropy/image-tests-py36-mpl222:1.10
    steps:
      - checkout
      - run:
          name: Install wheel
          command: pip3 install wheel
      - run:
          name: Install dependencies
          command: pip3 install .[test] codecov
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpl302:
    docker:
      - image: astropy/image-tests-py37-mpl302:1.10
    steps:
      - checkout
      - run:
          name: Install wheel
          command: pip3 install wheel
      - run:
          name: Install dependencies
          command: pip3 install .[test] codecov
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpl311:
    docker:
      - image: astropy/image-tests-py37-mpl311:1.10
    steps:
      - checkout
      - run:
          name: Install wheel
          command: pip3 install wheel
      - run:
          name: Install dependencies
          command: pip3 install .[test] codecov
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpldev:
    docker:
      - image: astropy/image-tests-py37-base:1.4
    steps:
      - checkout
      - run:
          name: Install wheel
          command: pip3 install wheel
      - run:
          name: Install Matplotlib
          command: pip3 install git+https://github.com/matplotlib/matplotlib.git
      - run:
          name: Install dependencies
          command: pip3 install .[test] codecov
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov


workflows:
  version: 2
  build_and_test:
    jobs:
      - image-tests-mpl212
      - image-tests-mpl222
      - image-tests-mpl302
      - image-tests-mpl311
      - image-tests-mpldev
