
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T11:31:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1ceacd6d61de4e3dcb487d0b75014dcbafcf939",
 "version": "0.7.1.post.dev403"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
