[dependencies]
ahash = "0.7"
glob = "0.3"
parking_lot = "0.12"
rayon = "1.5"

[dependencies.polars-arrow]
path = "../polars-arrow"
version = "0.19.1"

[dependencies.polars-core]
default-features = false
features = ["lazy", "private", "zip_with"]
path = "../polars-core"
version = "0.19.1"

[dependencies.polars-io]
default-features = false
features = ["lazy", "csv-file", "private"]
path = "../polars-io"
version = "0.19.1"

[dependencies.polars-time]
optional = true
path = "../polars-time"
version = "0.1.1"

[dependencies.polars-utils]
path = "../polars-utils"
version = "0.1.0"

[dependencies.regex]
optional = true
version = "1.5"

[features]
abs = ["polars-core/abs"]
arange = []
asof_join = ["polars-core/asof_join", "polars-time"]
bigidx = ["polars-arrow/bigidx", "polars-core/bigidx", "polars-utils/bigidx"]
compile = []
concat_str = ["polars-core/concat_str"]
cross_join = ["polars-core/cross_join"]
csv-file = ["polars-io/csv-file"]
cum_agg = ["polars-core/cum_agg"]
default = ["compile", "private"]
diff = ["polars-core/diff"]
dot_diagram = []
dot_product = ["polars-core/dot_product"]
dtype-categorical = ["polars-core/dtype-categorical"]
dtype-date = ["polars-core/dtype-date"]
dtype-datetime = ["polars-core/dtype-datetime"]
dtype-duration = ["polars-core/dtype-duration"]
dtype-i16 = ["polars-core/dtype-i16"]
dtype-i8 = ["polars-core/dtype-i8"]
dtype-struct = ["polars-core/dtype-struct"]
dtype-u16 = ["polars-core/dtype-u16"]
dtype-u8 = ["polars-core/dtype-u8"]
dynamic_groupby = ["polars-core/dynamic_groupby"]
ewma = ["polars-core/ewma"]
fmt = ["polars-core/fmt"]
future = []
interpolate = ["polars-core/interpolate"]
ipc = ["polars-io/ipc"]
is_first = ["polars-core/is_first"]
is_in = ["polars-core/is_in"]
list = ["polars-core/list"]
mode = ["polars-core/mode"]
moment = ["polars-core/moment"]
object = ["polars-core/object"]
panic_on_schema = []
parquet = ["polars-core/parquet", "polars-io/parquet"]
pct_change = ["polars-core/pct_change"]
private = ["polars-time/private"]
random = ["polars-core/random"]
rank = ["polars-core/rank"]
repeat_by = ["polars-core/repeat_by"]
rolling_window = ["polars-core/rolling_window"]
round_series = ["polars-core/round_series"]
strings = ["polars-core/strings"]
temporal = ["polars-core/temporal", "polars-time", "dtype-datetime"]
test = ["panic_on_schema", "private", "rolling_window", "rank", "list", "round_series", "csv-file", "dtype-categorical", "cum_agg", "regex", "polars-core/fmt", "diff", "abs", "parquet", "ipc"]
true_div = []

[package]
authors = ["ritchie46 <ritchie46@gmail.com>"]
description = "Lazy query engine for the Polars DataFrame library"
edition = "2021"
license = "MIT"
name = "polars-lazy"
repository = "https://github.com/pola-rs/polars"
version = "0.19.1"
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
