[package]
name = "usvg"
version = "0.22.0"
authors = [
    "Yevhenii Reizner <razrfalcon@gmail.com>",
]
keywords = [
    "svg",
]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification library."
categories = [
    "multimedia::images",
]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = [
    "testing-tools/**",
]

[[bin]]
name = "usvg"
required-features = [
    "filter",
    "text",
    "system-fonts",
    "memmap-fonts",
    "export",
]

[dependencies]
base64 = "0.13"
data-url = "0.1"
kurbo = "0.8"
log = "0.4"
pico-args = "0.4"
rctree = "0.4"
roxmltree = "0.14"
simplecss = "0.2.1"
siphasher = "0.3"
svgtypes = "0.8"

[dependencies.flate2]
version = "1.0"
default-features = false
features = [
    "rust_backend",
]

[dependencies.float-cmp]
version = "0.9"
default-features = false
features = [
    "std",
]

[dependencies.xmlwriter]
version = "0.1"
optional = true

[dependencies.fontdb]
version = "0.9"
optional = true
default-features = false

[dependencies.rustybuzz]
version = "0.5"
optional = true

[dependencies.ttf-parser]
version = "0.15"
optional = true

[dependencies.unicode-bidi]
version = "0.3"
optional = true

[dependencies.unicode-script]
version = "0.5"
optional = true

[dependencies.unicode-vo]
version = "0.1"
optional = true

[features]
default = [
    "filter",
    "text",
    "system-fonts",
    "memmap-fonts",
    "export",
]
filter = []
text = [
    "fontdb",
    "rustybuzz",
    "ttf-parser",
    "unicode-bidi",
    "unicode-script",
    "unicode-vo",
]
system-fonts = [
    "fontdb/fs",
    "fontdb/fontconfig",
]
memmap-fonts = [
    "fontdb/memmap",
]
export = [
    "xmlwriter",
]
