VERSION_YEAR = 2022
VERSION_MONTH = int('03')
VERSION_DAY = int('08')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('04')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202203081104
version_date = '2022/03/08 11:04'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
