# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ..configuration import Configuration


class ConquestApiHyperLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hyper_links': 'list[ConquestApiHyperLink]'
    }

    attribute_map = {
        'hyper_links': 'HyperLinks'
    }

    def __init__(self, hyper_links=None, _configuration=None):  # noqa: E501
        """ConquestApiHyperLinks - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hyper_links = None
        self.discriminator = None

        if hyper_links is not None:
            self.hyper_links = hyper_links

    @property
    def hyper_links(self):
        """Gets the hyper_links of this ConquestApiHyperLinks.  # noqa: E501


        :return: The hyper_links of this ConquestApiHyperLinks.  # noqa: E501
        :rtype: list[ConquestApiHyperLink]
        """
        return self._hyper_links

    @hyper_links.setter
    def hyper_links(self, hyper_links):
        """Sets the hyper_links of this ConquestApiHyperLinks.


        :param hyper_links: The hyper_links of this ConquestApiHyperLinks.  # noqa: E501
        :type: list[ConquestApiHyperLink]
        """

        self._hyper_links = hyper_links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiHyperLinks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiHyperLinks):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConquestApiHyperLinks):
            return True

        return self.to_dict() != other.to_dict()
