
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-07T11:33:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b53667acf33ccca3676be1f61bcee153f0f87453",
 "version": "0.7.1.post.dev415"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
