version = 1

exclude_patterns = ["martin_binance/binance_api*",
                    "martin_binance/margin/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
