[tool.poetry]
name = "rosys"
version = "v0.5.11"
description = "Modular Robot System With Elegant Automation Capabilities"
authors = ["Zauberzeug GmbH <info@zauberzeug.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/zauberzeug/rosys"
keywords = ["robot", "framework", "automation", "control", "steer"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
simplejson = "^3.17.2"
pyserial = "^3.5"
numpy = "^1.20.1"
retry = "^0.9.2"
aioserial = "^1.3.0"
aiohttp = "^3.7.4"
pydantic = "1.9"
asyncio = "^3.4.3"
nicegui = "0.7.10"
python-socketio = {extras = ["asyncio_client"], version = "^5.3.0"}
networkx = "^2.6.2"
more-itertools = "^8.10.0"
scipy = "^1.7.2"
opencv-contrib-python-headless = "^4.5.4"
yappi = "^1.3.3"
tabulate = "^0.8.9"
sh = "^1.14.2"
aenum = "^3.1.5"
pyloot = "^0.0.7"
objgraph = "^3.5.0"
opencv-python = "^4.5.5"
psutil = "^5.9.0"
coloredlogs = "^15.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-watch = "^4.2.0"
pytest-flakefinder = "^1.0.0"
pytest-profiling = "^1.7.0"
autopep8 = "^1.5.5"
debugpy = "^1.2.1"
line-profiler = "3.1.0"
icecream = "^2.1.0"
pytest-asyncio = "^0.15.1"
py-spy = "^0.3.10"

[build-system]
requires = [
    "setuptools>=30.3.0,<50",
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"
