import cv2

# Gaussian blur constants
BLUR_KERNEL_RATIO = 400
BLUR_SIGMA_X = 0

# Contour constants
CONTOUR_MODE = cv2.RETR_EXTERNAL
CONTOUR_METHOD = cv2.CHAIN_APPROX_SIMPLE
PERIMETER_ARC = 0.02
CONTOUR_VERTEX_Y = 0,1
CONTOUR_VERTEX_X = 0,0

# Contour Height constants
HEIGHT_FIRST_VERTEX = 0
HEIGHT_SECOND_VERTEX = 2
CONTOUR_HEIGHT_ROUND = -1

# Read Circle constants
MARK_PERCENT = 0.5
MARKED = 'X'
NOT_MARKED = 'O'

ANCHOR_AREA_PERCENTAGE = 1296 / (1024 * 1508)
MIN_ANCHOR_AREA_PERCENTAGE = ANCHOR_AREA_PERCENTAGE * 0.9
MAX_ANCHOR_AREA_PERCENTAGE = ANCHOR_AREA_PERCENTAGE * 1.1

ANCHOR_WIDTH_PERCENTAGE = 40 / (1024)
MIN_ANCHOR_WIDTH_PERCENTAGE = ANCHOR_WIDTH_PERCENTAGE * 0.9
MAX_ANCHOR_WIDTH_PERCENTAGE = ANCHOR_WIDTH_PERCENTAGE * 1.1
