[tool.poetry]
name = "sentry_django_settings"
version = "0.5.0"
description = "Easy Django-Sentry integration via Django settings."
authors = []
license = "BSD License"

[tool.poetry.dependencies]
python = "^3.6"
sentry-sdk = "*"
django = "*"
gitpython = "*"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-django = "^4.5.2"

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
