site_name: python-openhab
site_url: https://github.com/sim0nx/python-openhab
repo_url: https://github.com/sim0nx/python-openhab


theme:
  name: "material"
  font: false

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    watch:
      - openhab

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - admonition

nav:
  - Home: 'index.md'
  - API Documentation:
    - 'Client': 'api_client.md'
    - 'Items': 'api_items.md'
    - 'Types': 'api_types.md'
