
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T11:48:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff6701ba6a48ef83c503a3bab7754d6b898e1895",
 "version": "1.16.0.post.dev111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
