[tool.poetry]
name = "sholl"
version = "0.0.6"
description = "Generate or Updates Hombrew formulas for your python projects"
authors = ["jeremynac <jeremynac@hotmail.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.1"
jinja2 = "3.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sholl = 'sholl.sholl:main'
