#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['lenskit_hpf']

package_data = \
{'': ['*']}

install_requires = \
['lenskit==0.14.*', 'hpfrec==0.2.*']

extras_require = \
{'dev': ['flit >= 3',
         'packaging >= 20',
         'flake8 >= 3',
         'coverage >= 5',
         'pytest-cov >= 2.12'],
 'doc': ['lenskit[doc]'],
 'test': ['pytest >= 6', 'pytest-doctestplus >= 0.9']}

setup(name='lenskit-hpf',
      version='0.14.0',
      description='Hierarchical Poisson factorization for LensKit.',
      author=None,
      author_email='Michael Ekstrand <michaelekstrand@boisestate.edu>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>= 3.7',
     )
