# SPDX-FileCopyrightText: 2021-2022 SanderTheDragon <sanderthedragon@zoho.com>
#
# SPDX-License-Identifier: CC0-1.0

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"
