# Version file autogenerated by the build process
version = '0.9.2'
build = 1043
vcs_info = 'Git SHA1 3a52fefe committed on 2022-03-04'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.9.2"\nKSCONF_BUILD="1043"\nKSCONF_VCS_INFO="Git SHA1 3a52fefe committed on 2022-03-04"')
