[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
dependencies = [
	"numpy >=1.17.0",
	"scipy >=1.3.1",
	"matplotlib >=3.1.1",
]

[project]
name = "relife"
authors = [
	{name = "Thomas Guillon"},
	{name = "Michael Boulade"},
	{name = "Laura Cohen"},
	{name = "Lionel Figueroa"},
	{name = "Jovana Krstevska "},
	{name = "Sami Tazi"}
]
readme = "README.rst"
classifiers = ["License :: OSI Approved :: Apache Software License"]
requires-python = ">=3.7"
dynamic = ["version", "description"]

[project.optional-dependencies]
test = [
    "pytest >=2.7.3",
    "pytest-cov",
]
doc = [
	"sphinx >= 4.4.0",
	"sphinx-book-theme >= 0.2.0",
]

[project.urls]
Home = "https://github.com/rte-france/relife"
Documentation = "https://rte-france.github.io/relife/"

