
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T20:11:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f867baf041a4c06517b3cd843bd3624205aad6af",
 "version": "0.14.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
