language: python
python:
    - "3.8"
    - "3.9"
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
    - pip install pytest-cov
    - sudo apt-get remove r-base r-base-core r-base-dev r-recommended
    - sudo apt install -y gfortran
    - sudo apt install -y build-essential
    - sudo apt-get install libreadline6 libreadline6-dev
    - wget https://cran.r-project.org/src/base/R-4/R-4.0.0.tar.gz
    - tar -xzf R-4.0.0.tar.gz
    - cd R-4.0.0
    - ./configure --enable-R-shlib --with-pcre1
    - sudo make
    - sudo make install
    - cd ..
    - wget https://cran.r-project.org/src/contrib/Archive/spatstat.geom/spatstat.geom_2.3-1.tar.gz
    - wget https://cran.r-project.org/src/contrib/spatstat.data_2.1-2.tar.gz
    - wget https://cran.r-project.org/src/contrib/spatstat.utils_2.3-0.tar.gz
    - wget https://cran.r-project.org/src/contrib/deldir_1.0-6.tar.gz
    - wget https://cran.r-project.org/src/contrib/polyclip_1.10-0.tar.gz
    - sudo R CMD INSTALL polyclip_1.10-0.tar.gz
    - sudo R CMD INSTALL deldir_1.0-6.tar.gz
    - sudo R CMD INSTALL spatstat.utils_2.3-0.tar.gz
    - sudo R CMD INSTALL spatstat.data_2.1-2.tar.gz
    - sudo R CMD INSTALL spatstat.geom_2.3-1.tar.gz
    - export LD_LIBRARY_PATH=/usr/local/lib/R/lib/:$LD_LIBRARY_PATH
install:
    - pip install numpy
    - pip install -U numpy
    - pip install scikit-allel
    - pip install pandas
    - python setup.py install
script: pytest --cov=. --cov-report term-missing
after_success:
    - codecov
