VERSION_YEAR = 2022
VERSION_MONTH = int('03')
VERSION_DAY = int('10')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('31')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202203101231
version_date = '2022/03/10 12:31'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
