[tool.poetry]
name = "marketdataproviders"
version = "0.1.0"
description = "APIs around Market Data Providers"
authors = ["Kamal Advani <kamal.advani@namingcrisis.net>"]
readme = "README.md"
packages = [
    { include = "marketdataproviders", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.1"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^8.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
