[build-system]
requires = [
  "setuptools >= 40.6.0",
  "arrow==1.2.2",
  "bullet==2.2.0",
  "click==8.0.3",
  "pyfiglet==0.8.post1",
  "python-dateutil==2.8.2",
  "PyYAML==6.0",
  "six==1.16.0"
]
build-backend = "setuptools.build_meta"