RENAME_ATOMS = {
    "CTR": {"O": "O1", "OXT": "O2"},
    "NTR": {"H": "H1"},
    "ILE": {"CD1": "CD"},
    "CYS": {"HG": "HG1"},
    "SER": {"HG": "HG1"},
    "TYR": {"HH": "HH1"},
}

RESIDUE_REFSTATE = {
    "HSD": "HI0",
    "HSE": "HI1",
    "HSP": "HI2",
    "ARGN": "AR0",
    "ASPH": "AS0",
    "CYS1": "CYS",
    "CYS2": "CYS",
    "CYSH": "CY0",
    "GLUH": "GL0",
    "HISD": "HI0",
    "HISE": "HI1",
    "HISH": "HI2",
    "HISA": "HI0",
    "HISB": "HI1",
    "HISP": "HI2",
    "LYSH": "LY3",
    "LYSN": "LY0",
    "ISU": "CYS",
}

TITRATABLE_RESIDUES = (
    "LYS",
    "HIS",
    "ASP",
    "GLU",
    "SER",
    "THR",
    "CYS",
    "CTR",
    "NTR",
    "TYR",
)

PROTEIN_RESIDUES = (
    "ALA",
    "CYS",
    "ASP",
    "GLU",
    "PHE",
    "GLY",
    "HIS",
    "ILE",
    "LYS",
    "LEU",
    "MET",
    "ASN",
    "PRO",
    "GLN",
    "ARG",
    "SER",
    "THR",
    "VAL",
    "TRP",
    "TYR",
    "NTR",
    "CTR",
)