from .._exceptions import ReadError as ReadError
from .._mesh import Mesh as Mesh
from typing import Any

permas_to_meshio_type: Any
meshio_to_permas_type: Any

def read(filename): ...
def read_buffer(f): ...
def get_param_map(word, required_keys: Any | None = ...): ...
def read_set(f, params_map): ...
def write(filename, mesh) -> None: ...
