
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-10T06:52:47-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "66c4c0b73081c38fe291be02cfcf37989a1399dd",
 "version": "0.29.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
