_target_: 'classy.pl_modules.hf.generation.HFGenerationPLModule'
transformer_model: ${transformer_model}
additional_special_tokens: []
decoding_skip_special_tokens: True
decoding_clean_up_tokenization_spaces: False
optim_conf:
  _target_: classy.optim.factories.RAdamFactory
  lr: 1e-5
  weight_decay: 0.01
  no_decay_params:
    - bias
    - LayerNorm.weight
