
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-09T15:41:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "92bf86c1583de86678735e4260a7f6b7375f3ff4",
 "version": "0.0.67.post0.dev148"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
