[tool.poetry]
name = "es_orm"
version = "0.1.4"
description = "easy es helper"
authors = ["iulmt <1817556010@qq.com>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.6"
elasticsearch = "7.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
