
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T16:13:55-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "9886db23f7a75f480e378aeb4d1f039faeed167d",
 "version": "v2.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
