
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-05T20:34:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f357aca11178f5301ce8ff399c7eedc76ea5d40",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
