
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T14:00:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "771c0b21052867dd5d4ba251bb69025d3a01dcab",
 "version": "7.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
