[tool.poetry]
name = "robocorp-inspector-commons"
version = "0.2.0"
description = "Robocorp Inspector Commons"

authors = ["Robocorp <dev@robocorp.com>"]
repository = "https://github.com/robocorp/inspector"
license = "Proprietary"
readme = "README.md"

packages = [
	{ include = "inspector_commons" },
]

include = ["inspector_commons/static/**/*"]

[tool.poetry.dependencies]
python = "^3.7"
rpaframework-core = "^6.3.2"
requests = "^2.25.1"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
pylint = "^2.6.0"
flake8 = "^3.8.4"
pytest = "^6.2.1"
setuptools = "^51.1.2"
PyYAML = "^5.4.1"
mypy = "^0.800"

[tool.black]
target-version = ["py38"]

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
