[tool.poetry]
name = "kapow"
version = "0.2.2"
description = ""
authors = ["Mark Gemmill <mark@markgemmill.com>"]
maintainers = [
    "Mark Gemmill <dev@markgemmill.com>",
    "Jason Clarke <jay@jayscorner.com>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/markgemmill/kapow"
repository = "https://github.com/markgemmill/kapow"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Application Frameworks"
]
include = [
    "kapow/cli/resource/*.txt",
    "kapow/resources/logging.ini"
]

[tool.poetry.dependencies]
python = "^3.9"
tomlkit = "^0.9.2"
docopt-ng = "^0.7.2"
rich = "^11.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
coverage = "^6.3.1"
pytest-cov = "^3.0.0"
black = "^22.1.0"
dover = "^0.5.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kapow = "kapow.cli:main"

[tool.dover]
versioned_files = [
    "pyproject.toml",
    "kapow/__init__.py"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --cov=kapow tests"
testpaths = ["tests"]

[tool.coverage.run]
omit = ['kapow/appdirs.py', 'kapow/cli/*']

[tool.coverage.report]
show_missing=true

[tool.black]
exclude = "(sample.py|vcc_data.py)"

[tool.isort]
quiet = true
profile = "black"
force_single_line = true
no_lines_before=["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
