[tool.poetry]
name = "signed-pickle"
version = "0.0.2"
description = "Description"
authors = ["Daniel Sullivan <mumblepins@users.noreply.github.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/mumblepins/signed-pickle/"
documentation = "https://mumblepins.github.io/signed-pickle/"
readme = "README.md"
packages = [{ include = "signed_pickle", from ="src" }]

[tool.poetry.dependencies]
python = "^3.7"
lz4 = "^4.0.0"

[tool.poetry.dev-dependencies]
black = { version = "^22", allow-prereleases = true }
Sphinx = "^4.4"
sphinx-rtd-theme = "^1.0"
pre-commit = "^2.17.0"

[tool.poetry.extras]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
