# Generated by Django 3.2.12 on 2022-03-08 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devind_dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name.', max_length=255)),
                ('code', models.IntegerField(default=None, help_text='Code of department.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated date')),
                ('minister', models.ForeignKey(help_text='Responsible Minister.', null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, related_name='minister',
                                               to=settings.AUTH_USER_MODEL)),
                ('organizations',
                 models.ManyToManyField(help_text='Related organizations.', to='devind_dictionaries.Organization')),
                ('user', models.ForeignKey(help_text='Director of department.', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, related_name='user',
                                           to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(help_text='Users in departments.', related_name='users',
                                                 to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
