VERSION_YEAR = 2022
VERSION_MONTH = int('03')
VERSION_DAY = int('09')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('56')
MAJOR_VERSION = 0
MINOR_VERSION = 5
PATCH_VERSION = 202203090656
version_date = '2022/03/09 06:56'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
