[tool.poetry]
name = "caworker"
version = "0.1.1"
description = ""
authors = ["Gustavo Côrtes <gpcortes@gmail.com>"]
license = "MIT"
readme = "README.md"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
pycamunda = "^0.6.0"
requests = "^2.27.1"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
