name: Publish the docker image

on:
  push:
    branches:
      - main
    tags: [ 'v*' ]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    environment:
      name: Docker Hub
      url: https://hub.docker.com/r/konstin2/maturin
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-meta@v2
        id: meta
        with:
          images: konstin2/maturin
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=registry,ref=konstin2/maturin:buildcache
          cache-to: type=registry,ref=konstin2/maturin:buildcache,mode=max
