[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bibcites"
authors = [{name = "Mathieu Daëron", email = "mathieu@daeron.fr"}]
readme = "readme.md"
dynamic = ["version", "description"]
license = {text = "BSD-3-Clause"}
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: BSD License",
	"Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "opencitingpy >=0.1",
    "bibtexparser >=1.2",
    "click >=8.0",
]

[project.urls]
Home = "https://github.com/mdaeron/bibcites"

[project.scripts]
bibcites = "bibcites:cli"
