name: Pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python setup.py egg_info
        pip install -r *.egg-info/requires.txt
        pip install -r test-time-requirements.txt
    - name: Analysing the code with pylint
      run: |
        # TODO #682
        pylint --disable=fixme,invalid-name,missing-function-docstring,missing-class-docstring,too-many-arguments,too-many-locals,too-many-instance-attributes,too-few-public-methods,protected-access,too-many-statements,duplicate-code,too-many-branches $(git ls-files '*.py')
