[tool.poetry]
name = "sbmodder"
version = "0.1.0"
description = ""
authors = ["takumi2786 <takumi_1884@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.4.0"
GitPython = "^3.1.27"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sbmodder = "sbmodder.client:main"
