VERSION_YEAR = 2022
VERSION_MONTH = int('03')
VERSION_DAY = int('09')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202203091526
version_date = '2022/03/09 15:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
