
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-09T11:54:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5728b881922546066562845bc15945d38ee0bf83",
 "version": "4.9.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
