[[bin]]
name = "resvg"
required-features = ["filter", "text", "system-fonts", "memmap-fonts"]

[dependencies]
gif = "0.11"
log = "0.4"
pico-args = "0.4"
png = "0.17"
rgb = "0.8"
svgtypes = "0.8"
tiny-skia = "0.6.1"

[dependencies.jpeg-decoder]
default-features = false
features = ["platform_independent"]
version = "0.2"

[dependencies.svgfilters]
optional = true
path = "local_dependencies/svgfilters"
version = "0.4"

[dependencies.usvg]
default-features = false
path = "local_dependencies/usvg"
version = "0.22.0"

[dev-dependencies]
once_cell = "1.5"

[features]
default = ["filter", "text", "system-fonts", "memmap-fonts"]
dump-svg = ["usvg/export"]
filter = ["svgfilters", "usvg/filter"]
memmap-fonts = ["usvg/memmap-fonts"]
system-fonts = ["usvg/system-fonts"]
text = ["usvg/text"]

[package]
authors = ["Yevhenii Reizner <razrfalcon@gmail.com>"]
description = "An SVG rendering library."
edition = "2018"
exclude = ["tests"]
keywords = ["svg", "render", "raster", "skia"]
license = "MPL-2.0"
name = "resvg"
repository = "https://github.com/RazrFalcon/resvg"
version = "0.22.0"

[workspace]
