[tool.poetry]
name = "rath"
version = "0.1.21"
description = "aiohttp powered apollo like graphql client"
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
readme = "README.md"
packages = [{include = "rath"}]

[tool.poetry.dependencies]
python = "^3.7"
koil = "0.1.80"
aiohttp = "^3.8.1"
graphql-core = "^3.2.0"
pydantic = "^1.9.0"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^1.0.3"
tox = "^3.24.5"
pytest-cov = "^3.0.0"
black = "^21.12b0"
pydoc-markdown = "^4.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.pydoc-markdown.loaders]]
type = "python"
search_path = [ "rath" ]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.pydoc-markdown.renderer]
type = "docusaurus"
docs_base_path = "website/docs"
