[tool.poetry]
name = "eagers"
version = "0.4.2"
description = "Efficient Allocation of Grid Energy Resources including Storage"
authors = ["Dustin McLarty <dustin.mclarty@wsu.edu>"]
license = "MIT"
include = ["demo_files"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.16.4"
scipy = "^1.3.1"
matplotlib = "^3.1.1"
tables = "^3.6.1"
openpyxl = "^3.0.3"
ecos = "^2.0.7"
building-plus = {version = "^0.1.6", optional = true}

[tool.poetry.extras]
building-plus = ["building-plus"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = "test"
# Use single quotes for "raw" strings in TOML.
filterwarnings = [
    'ignore:`np\.\w+` is a deprecated alias for [` \w]+\.:DeprecationWarning',
]
