[tool.poetry]
name = "pyNFSeSP"
version = "0.1.0"
description = "Módulo para emissão de Notas Fiscais de Serviço para a Prefeitura de SP"
authors = ["Bruno Souza <bruno@komu.com.br>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.8.0"
pycrypto = "^2.6.1"
requests = "^2.27.1"
rsa = "^4.8"
urllib3 = "^1.26.8"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = {version = "^21.11b1", allow-prereleases = true}
isort = "^5.10.1"
mypy = "^0.910"
pylint = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
