[tool.poetry]
name = "eggfarm"
version = "0.1.0"
description = "A tool for generating stonewave table function"
authors = ["Yue Ni <niyue.com@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^2.11.3"
MarkupSafe = "2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
eggfarm = 'eggfarm.main:main'