[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.isort]
profile = "black"

[project]
name = "keygen_licensing_tools"
authors = [{name = "Nico Schlömer", email = "nico.schloemer@gmail.com"}]
description = "Python tools for Keygen.sh licensing"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Utilities",
]
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "cryptography",
    "requests",
    "ed25519",
]

[project.urls]
Code = "https://github.com/nschloe/keygen_licensing_tools"
Issues = "https://github.com/nschloe/keygen_licensing_tools/issues"
Funding = "https://github.com/sponsors/nschloe"
