[tool.poetry]
name = "arcane-pinterest"
version = "1.1.0"
description = "Helpers to request Pinterest API "
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
backoff = "^1.10.0"
requests = "^2.0.0"
arcane-core = "^1.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
