[tool.poetry]
name = "etchrepl"
version = "0.1.4"
description = "A repl for Etch. Nothing much to see here."
authors = ["GingerIndustries"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
toml = "^0.10.2"
etchlang = "*"

[tool.poetry.scripts]
etch = "etchrepl:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
