
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-03T11:44:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c46653f61c3489c74d1e06d37eb82665e0371e66",
 "version": "0.7.1.post.dev407"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
