
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T18:23:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3a9eb36ca47a482b4c933aca213b43381e007e1",
 "version": "7.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
