[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pywebid"
authors = [
    {name = "Kushal Das", email = "mail@kushaldas.in"},
]
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.6"
dynamic = ["version", "description"]

dependencies = [
    "rdflib",
]

[project.urls]
Documentation = "https://webid.readthedocs.io/en/latest/"
Source = "https://github.com/projectliquid/webid"

[tool.flit.sdist]
include = ["LICENSE", "README.md"]
exclude = ["docs/*.html", ".readthedocs.yaml", "dev*.*"]

[tool.flit.module]
name = "webid"
