
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-09T13:24:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "18f0742d4010015fc0d4dbb853584ffb1e193bcf",
 "version": "4.9.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
