
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-08T22:37:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aeb3fcb4f7a122bfdffaffca77450f79dcb93db9",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
