[tool.poetry]
name = "tl_scripts"
version = "0.1.1"
description = ""
authors = ["dorhar <doron.harnoy@tensorleap.ai>"]
include = ["tl_scripts_cli.py"]

[tool.poetry.dependencies]
python = "^3.6"
ndjson = "^0.3.1"
requests = "^2.27.1"
pexpect = "^4.8.0"
docopt = "^0.6.2"

[tool.poetry.scripts]
copy_kibana_objects = "tl_scripts_cli:__main__"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
