variables:
    CARGO_HOME: "${CI_PROJECT_DIR}/cargo"
    RELEASE_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-g${CI_COMMIT_SHORT_SHA}-b${CI_PIPELINE_ID}"
    TEST_PYPI_SERVER: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    TEST_PYPI_USER: "gitlab-ci-token"
    TEST_PYPI_PASSWORD: "${CI_JOB_TOKEN}"
    TEST_PYPI_INDEX_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/pypi/simple"

default:
    tags:
      - linux-docker

stages:
  - check
  - build
  - test
  - wheels
  - publish-test
  - install-test
  - deploy

image: ${PLG_CI_DOCKER_TAG}/rusty-python:latest

cache:
    key:
        files:
          - Cargo.lock
    paths:
      - cargo

prefetch:
    stage: .pre
    script:
      - mkdir -p .cargo
      - echo "[source.crates-io]" > .cargo/config
      - echo registry = \""${PLG_CI_CRATES_IO_MIRROR_INDEX}"\" >> .cargo/config
      - cargo fetch
    artifacts:
        paths:
          - .cargo

fmt:
    stage: check
    script:
      - cargo fmt -- --check

clippy:
    stage: check
    script:
      - cargo clippy -- --deny warnings

compile:
    stage: build
    script:
      - cargo build --release
      - mkdir -p dist
      - cp "target/release/lib${CI_PROJECT_NAME}.so" "dist/${CI_PROJECT_NAME}.so"
      - strip "dist/${CI_PROJECT_NAME}.so"
    artifacts:
        name: "${RELEASE_NAME}-bin-lin64"
        paths:
          - dist

compile-win64:
    stage: build
    script:
      - PYO3_CROSS_LIB_DIR=target/python3-dll cargo build --release --target x86_64-pc-windows-gnu
      - mkdir -p dist
      - cp "target/x86_64-pc-windows-gnu/release/${CI_PROJECT_NAME}.dll" "dist/${CI_PROJECT_NAME}.pyd"
      - x86_64-w64-mingw32-strip "dist/${CI_PROJECT_NAME}.pyd"
    artifacts:
        name: "${RELEASE_NAME}-bin-win64"
        paths:
          - dist

docs:
    stage: build
    script:
      - python3 -m venv --system-site-packages pdoc_venv
      - . pdoc_venv/bin/activate
      - maturin develop
      - python3 -m pdoc -o target/pdoc "${CI_PROJECT_NAME}"
    artifacts:
        name: "${RELEASE_NAME}-docs"
        paths:
          - target/pdoc

package:
    stage: wheels
    script:
      - maturin build --release --strip
      - cp -t dist target/wheels/*.whl
    artifacts:
        name: "${RELEASE_NAME}-wheel-lin64"
        paths:
          - dist

package-win64:
    stage: wheels
    script:
      - PYO3_CROSS_LIB_DIR=target/python3-dll maturin build --release --strip --target x86_64-pc-windows-gnu
      - cp -t dist target/wheels/*.whl
    artifacts:
        name: "${RELEASE_NAME}-wheel-win64"
        paths:
          - dist

package-sdist:
    stage: wheels
    script:
      - maturin sdist
      - cp -t dist target/wheels/*.tar.gz
    artifacts:
        name: "${RELEASE_NAME}-sdist"
        paths:
          - dist

typecheck:
    stage: test
    script:
      - python3 -m venv --system-site-packages mypy_venv
      - . mypy_venv/bin/activate
      - maturin develop
      - python3 -m pip install -U setuptools --index-url "${PLG_CI_PYPI_INDEX_URL}"
      - python3 -m pylint --extension-pkg-whitelist="${CI_PROJECT_NAME}" tests
      - python3 -m mypy tests

runtests:
    stage: test
    script:
      - tox --index-url "${PLG_CI_PYPI_INDEX_URL}"
      - python3 -m venv --system-site-packages test_venv
      - . test_venv/bin/activate
      - maturin develop
      - python3 -m unittest --verbose
      - python3 -m pytest --verbose

pubtest:
    stage: publish-test
    script:
      - maturin upload --skip-existing -r "${TEST_PYPI_SERVER}" -u "${TEST_PYPI_USER}" -p "${TEST_PYPI_PASSWORD}" dist/*.whl dist/*.tar.gz

test-install:
    stage: install-test
    image: ${PLG_CI_DOCKER_TAG}/python:latest
    script:
      - pip3 install "${CI_PROJECT_NAME}" --index-url "${TEST_PYPI_INDEX_URL}"
      - python3 -m unittest

test-install-win64:
    stage: install-test
    tags:
      - windows-docker
    image: ${PLG_CI_DOCKER_TAG}/python_2004:latest
    variables:
        ErrorActionPreference: stop
    script:
      - pip3 install "${CI_PROJECT_NAME}" --index-url "${TEST_PYPI_INDEX_URL}"
      - python -m unittest

test-install-sdist:
    stage: install-test
    image: ${PLG_CI_DOCKER_TAG}/rusty-python:latest
    script:
      - pip3 install "${CI_PROJECT_NAME}" --no-binary "${CI_PROJECT_NAME}" --index-url "${TEST_PYPI_INDEX_URL}"
      - python3 -m unittest

publish-wheels:
    stage: deploy
    only:
      - tags
    script:
      - maturin upload -r "${PLG_CI_PYPI_SERVER}" -u "${PLG_CI_PYPI_USER}" -p "${PLG_CI_PYPI_PASSWORD}" dist/*.whl dist/*.tar.gz

include:
  - project: 'devops/support'
    ref: master
    file: 'includes/artifacts/deploy-site.yml'

deploy-site:
    variables:
        DEPLOY_DIR: "target/pdoc"
        DEPLOY_STRATEGY: "custom"
        DEPLOY_PATH: "$CI_COMMIT_REF_NAME"
