[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 100
target-version = ["py39"]

[tool.sqlfluff.core]
exclude_rules = "L044"
dialect = "postgres"
[tool.sqlfluff.rules]
max_line_length = 100
[tool.sqlfluff.templater.jinja.context]
target = "dev"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
markers = [
    "e2e_cli: mark a test as a part of the e2e cli test suite",
    "e2e_etl: mark a test as a part of the e2e etl test suite"
]
