[tool.poetry]
name = "logging-actions"
version = "0.1.7"
description = "For easy configuration of `logging.Logger`s with `argparse.Action`s."
authors = ["Aatif Syed <aatifsyedyp@gmail.com>"]
repository = "https://github.com/aatifsyed/logging-actions"
readme = "README.md"

dependencies = { python = "^3.6.2" }
dev-dependencies = { pytest = "^6.0", black = "^21.6b0", mypy = "^0.910" }
include = ["logging_actions/py.typed"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
addopts = ["--doctest-glob=README.md"]
