[tool.poetry]
name = "xarray-dataclasses"
version = "1.0.0"
description = "xarray extension for typed DataArray and Dataset creation"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
keywords = ["xarray", "dataclass", "dataarray", "dataset", "typing"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/astropenguin/xarray-dataclasses/"
documentation = "https://astropenguin.github.io/xarray-dataclasses/"

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
morecopy = "^0.2"
more-itertools = "^8.12"
numpy = "^1.17"
typing-extensions = "^3.10"
xarray = ">=0.18, <0.30"

[tool.poetry.dev-dependencies]
black = "^22.1"
ipython = "^7.32"
myst-parser = "^0.17"
pydata-sphinx-theme = "^0.8"
pytest = "^7.0"
sphinx = "^4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
