[tool.poetry]
name = "cr_api_client"
version = "1.8.3"
description = "AMOSSYS Cyber Range client API"
readme = "README.md"
authors = ["AMOSSYS"]
packages = [
    { include = "cr_api_client" },
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
"ruamel.yaml" = "~0.16.10"
requests = "^2.24.0"
colorama = "~0.4.4"
termcolor = "~1.1.0"
loguru = "~0.5.3"
humanize = "^3.13.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
cyber_range = "cr_api_client.cyber_range:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
