[tool.poetry]
name = "aurelio"
version = "0.0.1"
description = "Python dictionary interface for key-value databases"
authors = ["KelvinS <kelvinpfw@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
redis = {version = "^4.1.4", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
bandit = "^1.7.4"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"

[tool.poetry.extras]
redis = ["redis"]

[tool.isort]
line_length = 79
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true

[tool.black]
line-length = 79
target-version = ["py37", "py38", "py39", "py310"]
skip-string-normalization = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
