
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-07T19:50:34-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "907991b31ba4543ffb90a33d957108181e520506",
 "version": "0.2.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
