[tool.poetry]
name = "bcf-api-xml"
version = "0.2.13"
description = "Convert BCF-API to BCF-XML"
authors = ["Hugo Duroux <hugo@bimdata.io>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bimdata/rabbitmq-subprocess-client"
repository = "https://github.com/bimdata/rabbitmq-subprocess-client"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.5.0"
generateDS = "^2.35.13"
python-dateutil = "^2.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
black = "^19.10b0"
pre-commit = "^2.1.1"
reorder-python-imports = "^2.0.0"
pyflakes = {git = "https://github.com/pycqa/pyflakes", rev = "1911c20"}
pycodestyle = {git = "https://github.com/pycqa/pycodestyle", rev = "d219c68"}

[tool.black]
line-length = 95
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

