[tool.poetry]
name = "mtv_dl"
version = "0.20.5"
description = "MediathekView Downloader"
readme = "DESCRIPTION.rst"
authors = ["Frank Epperlein <frank+mtv_dl@epperle.in>"]
repository = "https://github.com/fnep/mtv_dl"
license = "MIT License"
classifiers = [
    "Topic :: Multimedia :: Video",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: Public Domain",
    "Programming Language :: Python :: 3.6",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.6"
rfc6266 = "^0.0.4"
iso8601 = "^0.1.16"
docopt = "^0.6.2"
pydash = "^4.9.3"
durationpy = "0.5"
PyYAML = "^5.4.1"
beautifulsoup4 = "^4.10.0"
typing_extensions = "^3.10.0.2"
rich = "^10.11.0"
certifi = "^2021.10.8"

[tool.poetry.dev-dependencies]
mypy = "^0.931"
twine = "^3.8.0"
types-PyYAML = "^6.0.4"
types-certifi = "^2021.10.8"

[tool.poetry.scripts]
mtv_dl = 'mtv_dl:main'

[tool.poetry-dynamic-versioning]
enable = false
pattern = '^v(?P<base>\d+\.\d+)'
format = '{base}.{distance}'

[build-system]
requires = ["poetry>=1.0.2", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
