
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-04T10:08:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0f8cf64e918a0dcbb0b1e85aa6927eacdd27394",
 "version": "0.5.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
