dataset:
  _target_: 'classy.data.dataset.hf.classification.HFSequenceDataset.from_samples'
  transformer_model: ${transformer_model}
  additional_special_tokens: "${oc.select:'model.additional_special_tokens',${oc.decode:'[]'}}"
  min_length: -1
  max_length: -1
  tokens_per_batch: 800
  max_batch_size: -1
  section_size: 10000
  prebatch: True
  materialize: False
  for_inference: True
